plugins:
  discourse_custom_automations_enabled:
    default: false
    client: true

  send_email_on_new_post_email_recipient:
    default: ""
    client: true

  send_email_on_new_post_email_subject:
    default: "New Post Notification"
    client: true

  send_email_on_new_post_email_body:
    default: "A new post has been created."
    client: true
